# Generated by Django 4.1.5 on 2023-01-18 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_alter_game_away_goals_alter_game_home_goals'),
    ]

    operations = [
    ]
