# Generated by Django 4.1.5 on 2023-02-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='short',
        ),
    ]
