# Generated by Django 4.2.5 on 2023-10-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_alter_bet_user_standingprediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='away_goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='home_goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(related_name='competitions', to='betting.team'),
        ),
    ]
