# Generated by Django 4.2.5 on 2023-10-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_bet_points_alter_bet_away_goals_alter_bet_home_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
