# Generated by Django 4.1.5 on 2023-01-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_bet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
