# Generated by Django 4.2.5 on 2023-10-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_alter_game_away_goals_alter_game_home_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
