# Generated by Django 4.1.5 on 2023-01-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_auto_20230119_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_bets', to='betting.game'),
        ),
        migrations.AddConstraint(
            model_name='bet',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='one_bet_per_user_per_game'),
        ),
    ]
