# Generated by Django 5.0.3 on 2024-04-15 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_standingpredictionteam_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterField(
            model_name='standingprediction',
            name='most_assists',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='standingprediction',
            name='standing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='standingprediction',
            name='top_scorer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='standingpredictionteam',
            name='standing_prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_positions', to='betting.standingprediction'),
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('top_scorer', models.CharField(blank=True, max_length=100)),
                ('most_assists', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.competition')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('standing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_positions', to='betting.standing')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='standing',
            constraint=models.UniqueConstraint(fields=('competition', 'round'), name='one_standing_per_round_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='teamposition',
            constraint=models.UniqueConstraint(fields=('standing', 'position'), name='unique_position_per_standing'),
        ),
        migrations.AddConstraint(
            model_name='teamposition',
            constraint=models.UniqueConstraint(fields=('standing', 'team'), name='unique_team_per_standing'),
        ),
    ]
