# Generated by Django 5.0.3 on 2024-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_standingpredictionteam_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterField(
            model_name='standingprediction',
            name='most_assists',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='standingprediction',
            name='standing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='standingprediction',
            name='top_scorer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
