# Generated by Django 4.1.5 on 2023-02-04 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_alter_bet_game_bet_one_bet_per_user_per_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
