# Generated by Django 5.0.3 on 2024-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0007_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
    ]
