# Generated by Django 5.0.3 on 2024-06-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0008_competition_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='team_logos/'),
        ),
    ]
