# Generated by Django 5.2.12 on 2026-04-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0009_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='clean_sheets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standing',
            name='most_points',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='standingprediction',
            name='clean_sheets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standingprediction',
            name='most_points',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
